"""
Django settings for myproject project.

<<<<<<< HEAD
Generated by 'django-admin startproject' using Django 5.2.
=======
Generated by 'django-admin startproject' using Django 5.2.4.
>>>>>>> 58fe60e7d81f7bfbd5bbf72179b00ddf9e542bfb

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
<<<<<<< HEAD
=======
import os
>>>>>>> 58fe60e7d81f7bfbd5bbf72179b00ddf9e542bfb

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD
SECRET_KEY = 'django-insecure-!s43@fuvk*5o+$kqtwwiu8+j_8v(ilox4i@egui(8s*s)w(kq!'
=======
SECRET_KEY = 'django-insecure-*#30s%^ggo85i6!h-nlbhbzutcr$xcnq2=gkwga$$7*@6vipx6'
>>>>>>> 58fe60e7d81f7bfbd5bbf72179b00ddf9e542bfb

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

<<<<<<< HEAD
INSTALLED_APPS = [  
    'doctor',
=======
INSTALLED_APPS = [
>>>>>>> 58fe60e7d81f7bfbd5bbf72179b00ddf9e542bfb
    'myapp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
=======
>>>>>>> 58fe60e7d81f7bfbd5bbf72179b00ddf9e542bfb
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
<<<<<<< HEAD
    'allauth.account.middleware.AccountMiddleware',
=======
>>>>>>> 58fe60e7d81f7bfbd5bbf72179b00ddf9e542bfb
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

<<<<<<< HEAD
TIME_ZONE = 'UTC'
=======

TIME_ZONE = 'Asia/Kolkata'
>>>>>>> 58fe60e7d81f7bfbd5bbf72179b00ddf9e542bfb

USE_I18N = True

USE_TZ = True

<<<<<<< HEAD

=======
>>>>>>> 58fe60e7d81f7bfbd5bbf72179b00ddf9e542bfb
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
<<<<<<< HEAD
=======
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATICFILES_DIRS = [BASE_DIR / 'static']

>>>>>>> 58fe60e7d81f7bfbd5bbf72179b00ddf9e542bfb

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

<<<<<<< HEAD
RAZORPAY_KEY_ID = 'rzp_test_Tt3qOWfteEDZUV'
RAZORPAY_KEY_SECRET = '0scdY1TbswlCQNuzcMwLdsW0'

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

=======

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST_USER = 'nishapatel8399@gmail.com'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
>>>>>>> 58fe60e7d81f7bfbd5bbf72179b00ddf9e542bfb
