# Generated by Django 5.2.4 on 2025-08-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_category_user_profile_image_user_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemedia',
            name='file',
            field=models.FileField(upload_to='uploads/media/'),
        ),
    ]
