# Generated by Django 5.2 on 2025-05-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
