# Generated by Django 5.2 on 2025-07-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='latitude',
            field=models.FloatField(default=20.5937),
        ),
        migrations.AddField(
            model_name='doctor',
            name='longitude',
            field=models.FloatField(default=78.9629),
        ),
    ]
